### ISSUE TITLE
Workers exit in choose_pool when using mpi

### ISSUE THREAD

**Issue by adgress** [adrn/schwimmbad#1]
I noticed the following lines in **init**.py::choose_pool

if not pool.is_master():
      sys.exit(0)

This seems to cause all workers to exit after constructing the MPIPool.  Am I missing something?

**Comment by adrn** [comment]
The workers are all told to wait for messages from the master processes (in the constructor) and then, when they are done, exit. It's there so that when they're done receiving tasks, the script isn't executed on all of the worker processes. Does that make sense?
