### ISSUE TITLE
TOC doesn't appear on most docs pages

### ISSUE THREAD

**Issue by dfm** [adrn/schwimmbad#13]
e.g.

<img width="363" alt="screen shot 2017-08-10 at 7 10 11 am" src="https://user-images.githubusercontent.com/350282/29174403-11d8cc9c-7d9b-11e7-823c-5dd5477e048e.png">

It would probably be good to add this unless there was a reason why you didn't want it.

**Comment by adrn** [comment]
I think this is fixed now!
