### ISSUE TITLE
use context manager?

### ISSUE THREAD

**Issue by beckermr** [adrn/schwimmbad#20]
It might be nice to use a context manager for things like close methods?

**Comment by adrn** [comment]
Agreed! I can try to get to this in a few weeks (busy with job interviews over the next few weeks), but if anyone else wants to have a go at implementing this, feel free.

**Comment by dfm** [comment]
Wait - isn't this already implemented? I always use this as a context manager. Am I missing something?

**Comment by adrn** [comment]
Oh right - I thought that was only implemented on the `MultiPool`, but it looks like it should work for all of them!

**Comment by adrn** [comment]
Can you clarify @beckermr?

**Comment by beckermr** [comment]
I didn't see it for the MPI pool. I probably missed it in the base class! Sorry!

**Comment by dfm** [comment]
No worries! Thanks for checking in.
