### ISSUE TITLE
I fixed some issues I had with MPIPool

### ISSUE THREAD

**Issue by uweschmitt** [adrn/schwimmbad#23]
I had two issues with your current implementation of `MPIPool`:

1. Exceptions in the worker processes did not shutdown the pool, thus my applications froze.
2. `MPIPool` starts the worker tasks within the `map` implementations which then return `None` after some time. This does not cause problems if your code only calls `map` and exits afterwards, but using `map` multiple times in a script gave strange results and errors.

I implemented solutions for this in https://gitlab.com/uweschmitt/mpipool, maybe you want to integrate this solution in `schwimmbad`. I had no time to create a proper pull request.

**Comment by floydie7** [comment]
I would like to second this issue. 

1. I've had a few situations lately where exceptions were being raised by tasks in the worker processes that left the program hanging until the HPC killed the job for time out.
2. This explains why I had issues in the past when I tried to reuse the pool downstream.

What can we do to move this along to bring these solutions into schwimmbad?

**Comment by uweschmitt** [comment]
Thanks for the support. I was thinking about incorporating my changes into `schwimmbad` and create a merge request. This would be the appropriate contribution as I also benefit from `schimmbad`  but it would also involve a significant of amount of work and I just don't have enough time.

I can try to explain what I did and hopefully others here will pick up my ideas and find a good design to fix this within `schwimmbad`.

I'm not an MPI expert, so I hope I use the right terms below. For me workers are MPI processes with a rank larger than 0. The master is the process with rank 0.

## Problem 2
The cause for Problem 2 is that in the existing implementation of `schwimmbad`  all MPI processes (workers and master)  enter the `map` function.

When `map` returns the workers return `None`, only the master returns a real result. So in case the MPI processes continue after `map` we have inconsistent results from `map`.

My solution is to block the workers as soon as you run

```
with Pool() as pool:
    ...
```

This blocking happens here: https://gitlab.com/uweschmitt/mpipool/blob/master/mpipool/mpipool.py#L35

Workers block as soon as we instantiate `Pool` and handle work until the program ends or a worker throws an exception.

## Problem 1
In case an worker throws an exception it is handled here:
https://gitlab.com/uweschmitt/mpipool/blob/master/mpipool/mpipool.py#L38 

The exception hander then:
- prints a traceback to support debugging
- shuts down all MPI processes to avoid hanging.

As we block the workers early, it might happen that the master tries to run a function which is not present in the workers global namespace.

The solution for this is to serialise the arguments but also the function and pass the full result to the worker: https://gitlab.com/uweschmitt/mpipool/blob/master/mpipool/mpipool.py#L35

The worker in turn reconstructs  function and arguments and finally executes the function for the given arguments: https://gitlab.com/uweschmitt/mpipool/blob/master/mpipool/mpipool.py#L18

I used `dill` instead of `pickle` because `dill` also can handle corner cases as `lambda` functions or static methods.

The approach to also serialise the function can cause some overhead as the full global namespace is also transferred, but as using MPI with Python only makes sense if function execution itself has a significant execution time I assume this overhead is tolerable.

I hope this explanation is somehow understandable don't hesitate to ask further questions.

**Comment by uweschmitt** [comment]
Just discovered that the comment https://gitlab.com/uweschmitt/mpipool/blob/master/mpipool/mpipool.py#L48 
is not correct. It relates to previous attempt where I made workers wait as soon `import mpipool` is executed.
