### ISSUE TITLE
SerialPool not starting

### ISSUE THREAD

**Issue by AlecThomson** [adrn/schwimmbad#26]
Hi there,

I'm currently using version 0.3.0:
```python
In [1]: import schwimmbad
In [2]: schwimmbad.__version__
Out[2]: '0.3.0'
```
I'm finding that I can't get SerialPool to begin working. Here's a simple script which reproduces the problem:
```python
import schwimmbad

with schwimmbad.MultiPool() as pool:
    inputs = [i for i in range(0,10)]
    pool.map(print, inputs)

with schwimmbad.SerialPool() as pool:
    inputs = [i for i in range(10,20)]
    pool.map(print, inputs)
```
The only output I get is 0..10. I've found the same problem on more complex examples, with my own functions, and with and without `with` statements.

Cheers

**Comment by dfm** [comment]
Does the program hang or exit after that display? What happens if you put a `list` call around both of the `pool.map` lines?  Thanks!

**Comment by AlecThomson** [comment]
It doesn't hang, just exits like you would expect.

The `list` call worked! Is that the expected behaviour, or more of a workaround?

**Comment by dfm** [comment]
Great! That's the behavior I would expect (map should return an iterator) so I'm surprised that the MultiPool isn't the same!
