### ISSUE TITLE
Progress bar in MultiPool

### ISSUE THREAD

**Issue by Cyberface** [adrn/schwimmbad#29]
Hi,

Is it possible to use something like tqdm to show a progress bar in a `MultiPool` call?

Thanks!

**Comment by ahnitz** [comment]
@Cyberface Seb, you could do something like what we've done in gwastro/pycbc and have a variable that counts the number of calls that are done? Does that serve your purpose. I.E. https://github.com/gwastro/pycbc/blob/master/pycbc/pool.py#L35. That could be updated to cause a tqdm update I suppose.

**Comment by Cyberface** [comment]
Thanks @ahnitz I will give it a go - I might just import pycbc's pool tbh
