### ISSUE TITLE
Annoying coverage reporting

### ISSUE THREAD

**Issue by dfm** [adrn/schwimmbad#37]
**Related to the move to GitHub Actions**

We're getting a lot of noise from coveralls which I don't totally understand because I don't see that in my other projects that use this workflow. I expect there's some leftover setting from the Travis days either on GitHub or on coveralls. I'm not sure what it would be because I don't have access to either, but maybe you can audit the settings @adrn? Let me know what you discover.

<img width="355" alt="Screen Shot 2021-02-25 at 10 51 32 AM" src="https://user-images.githubusercontent.com/350282/109178995-709b0600-7757-11eb-86d7-5eb9f8db89e2.png">

**Comment by adrn** [comment]
Weird - no idea what's causing this! I removed a stagnant travis webhook, but everything else looks ok. Maybe this is related to the parallel builds?

**Comment by dfm** [comment]
Yeah - it's definitely something related to parallel builds, but I don't have this same issue when I use this same setup on other repos :/ I'll look into it later!
