### ISSUE TITLE
Always one MPI slave blocked, when pass in one Class

### ISSUE THREAD

**Issue by thebiggod** [adrn/schwimmbad#44]
I have a lot of parameters to set, so first I pass in the whole class as one parameter to one function which is used to deal with MPI task, however I find that sometimes there is always one MPI blocked eg: 60 tasks distributed to 15 MPI processes,  and at last only 59 tasks be worked out with one task blocked, and the program cannot exit succussfully because with one MPI process blocked!
 Then I tried to use the Class with __call__ method to deal with the 60tasks and the result is the same: sometimes all 60 tasks pass, sometimes onle 59 tasks pass.
![屏幕截图 2022-06-29 054021](https://user-images.githubusercontent.com/35368636/176304390-9445d657-4f28-4e57-a066-e9c2c4ab609f.png)
As you can see when the 1 MPI process is blocked , all MPI processes showes 100 percent CPU usage. 
Maybe it is because my Class is a little bit big?

**Comment by thebiggod** [comment]
The problem worked out!
 I uninstall the 0.3.2 version and use the 0.3.0 version, and everything goes well.

**Comment by adrn** [comment]
Sorry I never got to this. If I understand your question / comment correctly, I think this is expected: one process (rank 0) is always used as the "coordinating" process that sends tasks to the others. If you want to keep discussing, please reopen the issue. Sorry again to let so much time go by without responding!
