### ISSUE TITLE
Error using v0.4.0 in tests with github actions 

### ISSUE THREAD

**Issue by mcuntz** [adrn/schwimmbad#48]
Dear Adrian,

great that you update schwimmbad again. I find at a fantastic package.

Unfortunately, my github actions with Python >= 3.9 fail now for packages that use schwimmbad. See for example [pyeee](https://github.com/mcuntz/pyeee/actions/runs/8163685697/job/22317472624) in `Run tests`. pytest tells:
```
def choose_pool(
...
>       if processes != 1 and MultiPool.enabled():
E       UnboundLocalError: local variable 'MultiPool' referenced before assignment

```

Kind regards,
Matthias

**Comment by adrn** [comment]
Thanks for catching this! I was shocked to see there aren't any tests of `choose_pool()`, so I totally missed this 😓. I just pushed a regression test and a fix for this issue -- I'll cut a new release now!

**Comment by adrn** [comment]
v0.4.1 should be available now (or soon) on pypi! 
https://pypi.org/project/schwimmbad/0.4.1/

**Comment by mcuntz** [comment]
My check run again :-) Thanks.
